# Generated by Django 3.1.2 on 2023-02-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDeatils',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('details', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
    ]
