# Generated by Django 4.1.4 on 2023-02-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_file_product_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('customer_email', models.CharField(max_length=100)),
                ('payment_method_type', models.CharField(max_length=100)),
                ('payment_status', models.CharField(max_length=100)),
                ('order_status', models.CharField(max_length=100)),
            ],
        ),
    ]
